server:
  port: ${PORT}

spring:
  datasource:
    url: ${POSTGRE_DATABASE_URL}
    username: ${POSTGRE_USER}
    password: ${POSTGRE_PASSWORD}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20

  data:
    mongodb:
      uri: ${MONGODB_URI}